[package]
name = "d-sh"
version = "0.0.4"
authors = ["Emeric MARTINEAU"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
glob = "0.2"
users = "0.7"
dirs = "1.0"

[dev-dependencies]
regex = "1"
